name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run : 
        ls -l
        echo 'Docker login'
        docker login -u diksha0902
        echo 'Running build...'
        docker build . -t diksha0902/dockerdemo-1:latest
        echo 'Pushing image...'
        docker push diksha0902/dockerdemo-1:latest
        echo 'Done!'
    
